# Generated by Django 3.0.5 on 2020-05-13 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=50, unique=True)),
                ('contact', models.CharField(default=None, max_length=150)),
                ('password', models.CharField(default=None, max_length=150)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 17, 40, 13, 115524))),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
