# Generated by Django 3.0.6 on 2020-05-13 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200513_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 23, 57, 32, 478982)),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 23, 57, 32, 478903)),
        ),
    ]
